<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="7" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-05T15:42:04 IST" name="crudOperations.Test" finished-at="2024-04-05T15:42:14 IST" duration-ms="10453">
    <groups>
    </groups>
    <test started-at="2024-04-05T15:42:04 IST" name="Command line test" finished-at="2024-04-05T15:42:14 IST" duration-ms="10453">
      <class name="crudOperations.Test">
        <test-method signature="createValidUser()[pri:1, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:04 IST" name="createValidUser" description="Verify successful user creation with valid details" finished-at="2024-04-05T15:42:06 IST" duration-ms="2676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createValidUser -->
        <test-method signature="createInvalidUser()[pri:2, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:06 IST" name="createInvalidUser" description="Verify create user with invalid data inputs" finished-at="2024-04-05T15:42:07 IST" duration-ms="977" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInvalidUser -->
        <test-method signature="updateValidUser()[pri:3, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:07 IST" name="updateValidUser" description="Verify update user details with updated data for a valid user" finished-at="2024-04-05T15:42:08 IST" duration-ms="1057" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [422]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [422]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at crudOperations.Test.updateValidUser(Test.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateValidUser -->
        <test-method signature="updateInvalidUser()[pri:4, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:08 IST" name="updateInvalidUser" description="Verify update user details with invalid data for valid user" finished-at="2024-04-05T15:42:10 IST" duration-ms="1189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateInvalidUser -->
        <test-method signature="fetchValidUser()[pri:5, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:10 IST" name="fetchValidUser" description="Verify fetch user details of a valid user" finished-at="2024-04-05T15:42:11 IST" duration-ms="1116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fetchValidUser -->
        <test-method signature="fetchInvalidUser()[pri:6, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:11 IST" name="fetchInvalidUser" description="Verify fetch user details of an invalid user" finished-at="2024-04-05T15:42:12 IST" duration-ms="1053" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fetchInvalidUser -->
        <test-method signature="deleteValidUser()[pri:7, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:12 IST" name="deleteValidUser" description="Verify delete user operation for a valid user" finished-at="2024-04-05T15:42:13 IST" duration-ms="1170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteValidUser -->
        <test-method signature="deleteInvalidUser()[pri:8, instance:crudOperations.Test@b62fe6d]" started-at="2024-04-05T15:42:13 IST" name="deleteInvalidUser" description="Verify delete user with invalid authorization token" finished-at="2024-04-05T15:42:14 IST" duration-ms="1151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteInvalidUser -->
      </class> <!-- crudOperations.Test -->
    </test> <!-- Command line test -->
  </suite> <!-- crudOperations.Test -->
</testng-results>
